# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchos', '0005_auto_20160211_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchfootball',
            name='goalsawayteam',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchfootball',
            name='goalshometeam',
            field=models.IntegerField(null=True),
        ),
    ]
