# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchos', '0006_auto_20160211_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchfootball',
            name='league_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
