# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchos', '0007_matchfootball_league_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchfootball',
            old_name='league_id',
            new_name='season_id',
        ),
    ]
