# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchos', '0008_auto_20160211_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFootball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wins', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('draw', models.IntegerField()),
            ],
        ),
    ]
