# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchos', '0009_teamfootball'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfootball',
            name='teamid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
